-- Net Lab3_P8_Corrigido - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2015 


Library IEEE;
Use IEEE.STD_LOGIC_1164.ALL;
Use IEEE.STD_LOGIC_ARITH.ALL;
Use IEEE.STD_LOGIC_UNSIGNED.ALL;


Entity Lab3_P8_Corrigido_main IS
Port(
    Clk : IN STD_LOGIC;
    Enable : IN STD_LOGIC;
    Reset : IN STD_LOGIC
);
End Lab3_P8_Corrigido_main;



Architecture Structural OF Lab3_P8_Corrigido_main IS

  -- Component Definition:
  Component Lab3_P8_Corrigido IS
  Port(
      Clk : IN STD_LOGIC;
      in1 : IN STD_LOGIC;
      ini : IN STD_LOGIC;
      ini_2 : IN STD_LOGIC;
      outi_2 : IN STD_LOGIC;
      outi_3 : IN STD_LOGIC;
      ini_3 : IN STD_LOGIC;
      outi : IN STD_LOGIC;
      movei : OUT STD_LOGIC;
      Bot1 : OUT STD_LOGIC;
      movei_2 : OUT STD_LOGIC;
      Bot2 : OUT STD_LOGIC;
      movei_3 : OUT STD_LOGIC;
      Bot3 : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component Lab3_P8_Corrigido;

  -- Internal signals:

BEGIN

    U_Lab3_P8_Corrigido : Lab3_P8_Corrigido Port Map(
        Clk => Clk,
        in1 => '0',
        ini => '0',
        ini_2 => '0',
        outi_2 => '0',
        outi_3 => '0',
        ini_3 => '0',
        outi => '0',
         -- movei => ,
         -- Bot1 => ,
         -- movei_2 => ,
         -- Bot2 => ,
         -- movei_3 => ,
         -- Bot3 => ,
        Enable => Enable,
        Reset => Reset
    );

End Structural;
