-- Net Lab3_P8_Corrigido - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2014 




  -- Component Definition:
  Component Lab3_P8_Corrigido IS
  Port(
      Clk : IN STD_LOGIC;
      in1 : IN STD_LOGIC;
      ini : IN STD_LOGIC;
      ini_2 : IN STD_LOGIC;
      outi_2 : IN STD_LOGIC;
      outi_3 : IN STD_LOGIC;
      ini_3 : IN STD_LOGIC;
      outi : IN STD_LOGIC;
      movei : OUT STD_LOGIC;
      Bot1 : OUT STD_LOGIC;
      movei_2 : OUT STD_LOGIC;
      Bot2 : OUT STD_LOGIC;
      movei_3 : OUT STD_LOGIC;
      Bot3 : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component Lab3_P8_Corrigido;



    -- Port Map Template:
    U_Lab3_P8_Corrigido : Lab3_P8_Corrigido Port Map(
        Clk => clk,
        in1 => in1,
        ini => ini,
        ini_2 => ini_2,
        outi_2 => outi_2,
        outi_3 => outi_3,
        ini_3 => ini_3,
        outi => outi,
        movei => movei,
        Bot1 => Bot1,
        movei_2 => movei_2,
        Bot2 => Bot2,
        movei_3 => movei_3,
        Bot3 => Bot3,
        Enable => enable,
        Reset => reset
    );

