-- Net CSR___Lab_3___Part1 - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2015 


Library IEEE;
Use IEEE.STD_LOGIC_1164.ALL;
Use IEEE.STD_LOGIC_ARITH.ALL;
Use IEEE.STD_LOGIC_UNSIGNED.ALL;


Entity CSR___Lab_3___Part1_main IS
Port(
    Clk : IN STD_LOGIC;
    Enable : IN STD_LOGIC;
    Reset : IN STD_LOGIC
);
End CSR___Lab_3___Part1_main;



Architecture Structural OF CSR___Lab_3___Part1_main IS

  -- Component Definition:
  Component CSR___Lab_3___Part1 IS
  Port(
      Clk : IN STD_LOGIC;
      out1 : IN STD_LOGIC;
      in1 : IN STD_LOGIC;
      in2 : IN STD_LOGIC;
      in3 : IN STD_LOGIC;
      out2 : IN STD_LOGIC;
      out3 : IN STD_LOGIC;
      in4 : IN STD_LOGIC;
      movei : OUT STD_LOGIC;
      Bot1 : OUT STD_LOGIC;
      movei_4 : OUT STD_LOGIC;
      Bot1_2 : OUT STD_LOGIC;
      movei_5 : OUT STD_LOGIC;
      Bot1_3 : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component CSR___Lab_3___Part1;

  -- Internal signals:

BEGIN

    U_CSR___Lab_3___Part1 : CSR___Lab_3___Part1 Port Map(
        Clk => Clk,
        out1 => '0',
        in1 => '0',
        in2 => '0',
        in3 => '0',
        out2 => '0',
        out3 => '0',
        in4 => '0',
         -- movei => ,
         -- Bot1 => ,
         -- movei_4 => ,
         -- Bot1_2 => ,
         -- movei_5 => ,
         -- Bot1_3 => ,
        Enable => Enable,
        Reset => Reset
    );

End Structural;
