-- Net CSR___Lab3___Part4 - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2015 


Library IEEE;
Use IEEE.STD_LOGIC_1164.ALL;
Use IEEE.STD_LOGIC_ARITH.ALL;
Use IEEE.STD_LOGIC_UNSIGNED.ALL;


Entity CSR___Lab3___Part4_main IS
Port(
    Clk : IN STD_LOGIC;
    Enable : IN STD_LOGIC;
    Reset : IN STD_LOGIC
);
End CSR___Lab3___Part4_main;



Architecture Structural OF CSR___Lab3___Part4_main IS

  -- Component Definition:
  Component CSR___Lab3___Part4 IS
  Port(
      Clk : IN STD_LOGIC;
      ini : IN STD_LOGIC;
      outi : IN STD_LOGIC;
      ini_2 : IN STD_LOGIC;
      outi_2 : IN STD_LOGIC;
      ini_3 : IN STD_LOGIC;
      outi_3 : IN STD_LOGIC;
      in1 : IN STD_LOGIC;
      Bot1_i : IN STD_LOGIC;
      Bot2_i : IN STD_LOGIC;
      Bot3_i : IN STD_LOGIC;
      movei_i : IN STD_LOGIC;
      movei_2_i : IN STD_LOGIC;
      movei_3_i : IN STD_LOGIC;
      Bot1 : OUT STD_LOGIC;
      Bot2 : OUT STD_LOGIC;
      Bot3 : OUT STD_LOGIC;
      movei : OUT STD_LOGIC;
      movei_2 : OUT STD_LOGIC;
      movei_3 : OUT STD_LOGIC;
      in1_o : OUT STD_LOGIC;
      ini_o : OUT STD_LOGIC;
      outi_o : OUT STD_LOGIC;
      ini_2_o : OUT STD_LOGIC;
      outi_2_o : OUT STD_LOGIC;
      ini_3_o : OUT STD_LOGIC;
      outi_3_o : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component CSR___Lab3___Part4;

  -- Internal signals:

BEGIN

    U_CSR___Lab3___Part4 : CSR___Lab3___Part4 Port Map(
        Clk => Clk,
        ini => '0',
        outi => '0',
        ini_2 => '0',
        outi_2 => '0',
        ini_3 => '0',
        outi_3 => '0',
        in1 => '0',
        Bot1_i => '0',
        Bot2_i => '0',
        Bot3_i => '0',
        movei_i => '0',
        movei_2_i => '0',
        movei_3_i => '0',
         -- Bot1 => ,
         -- Bot2 => ,
         -- Bot3 => ,
         -- movei => ,
         -- movei_2 => ,
         -- movei_3 => ,
         -- in1_o => ,
         -- ini_o => ,
         -- outi_o => ,
         -- ini_2_o => ,
         -- outi_2_o => ,
         -- ini_3_o => ,
         -- outi_3_o => ,
        Enable => Enable,
        Reset => Reset
    );

End Structural;
