/* Net CSR___Lab_3___Part1 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include <stdlib.h>
#include "net_types.h"


#if defined(HTTP_SERVER) || defined(DBG_INFO)

static iopt_param_info CSR___Lab_3___Part1_input_info[] = {
    { "outi", 0 },
    { "ini", 0 },
    { "outi_2", 0 },
    { "ini_2", 0 },
    { "outi_3", 0 },
    { "ini_3", 0 },
    { "in1", 0 },
    { NULL, 0 }
};

static iopt_param_info CSR___Lab_3___Part1_output_info[] = {
    { "movei", 0 },
    { "movei_2", 0 },
    { "movei_3", 0 },
    { "Bot1", 0 },
    { "Bot2", 0 },
    { "Bot3", 0 },
    { NULL, 0 }
};

static iopt_param_info CSR___Lab_3___Part1_marking_info[] = {
    { "p_4", 0 },
    { "p_5", 0 },
    { "p_6", 0 },
    { "p_8", 0 },
    { "p_9", 0 },
    { "p_34_4", 0 },
    { "p_34_5", 0 },
    { "p_34_6", 0 },
    { "p_34_8", 0 },
    { "p_34_9", 0 },
    { "p_36_4", 0 },
    { "p_36_5", 0 },
    { "p_36_6", 0 },
    { "p_36_8", 0 },
    { "p_36_9", 0 },
    { "p_43", 0 },
    { "p_46", 0 },
    { "p_49", 0 },
    { "p_52", 0 },
    { "p_55", 0 },
    { "p_58", 0 },
    { "p_61", 0 },
    { NULL, 0 }
};

static iopt_param_info CSR___Lab_3___Part1_tfired_info[] = {
    { "t_10", 0 },
    { "t_11", 0 },
    { "t_12", 0 },
    { "t_13", 0 },
    { "t_25", 0 },
    { "t_34_10", 0 },
    { "t_34_11", 0 },
    { "t_34_12", 0 },
    { "t_34_13", 0 },
    { "t_34_25", 0 },
    { "t_36_10", 0 },
    { "t_36_11", 0 },
    { "t_36_12", 0 },
    { "t_36_13", 0 },
    { "t_36_25", 0 },
    { "t_39", 0 },
    { NULL, 0 }
};

iopt_param_info* get_CSR___Lab_3___Part1_InputInfo()
{
    CSR___Lab_3___Part1_InputSignals* inputs = get_CSR___Lab_3___Part1_InputSignals();
    CSR___Lab_3___Part1_input_info[0].value = inputs->outi;
    CSR___Lab_3___Part1_input_info[1].value = inputs->ini;
    CSR___Lab_3___Part1_input_info[2].value = inputs->outi_2;
    CSR___Lab_3___Part1_input_info[3].value = inputs->ini_2;
    CSR___Lab_3___Part1_input_info[4].value = inputs->outi_3;
    CSR___Lab_3___Part1_input_info[5].value = inputs->ini_3;
    CSR___Lab_3___Part1_input_info[6].value = inputs->in1;
    return CSR___Lab_3___Part1_input_info;
}

iopt_param_info* get_CSR___Lab_3___Part1_OutputInfo()
{
    CSR___Lab_3___Part1_PlaceOutputSignals* place_out = get_CSR___Lab_3___Part1_PlaceOutputSignals();
    CSR___Lab_3___Part1_EventOutputSignals* ev_out = get_CSR___Lab_3___Part1_EventOutputSignals();
    CSR___Lab_3___Part1_output_info[0].value = place_out->movei;
    CSR___Lab_3___Part1_output_info[1].value = place_out->movei_2;
    CSR___Lab_3___Part1_output_info[2].value = place_out->movei_3;
    CSR___Lab_3___Part1_output_info[3].value = place_out->Bot1;
    CSR___Lab_3___Part1_output_info[4].value = place_out->Bot2;
    CSR___Lab_3___Part1_output_info[5].value = place_out->Bot3;
    return CSR___Lab_3___Part1_output_info;
}

iopt_param_info* get_CSR___Lab_3___Part1_MarkingInfo()
{
    CSR___Lab_3___Part1_NetMarking* marking = get_CSR___Lab_3___Part1_NetMarking();
    CSR___Lab_3___Part1_marking_info[0].value = marking->p_4;
    CSR___Lab_3___Part1_marking_info[1].value = marking->p_5;
    CSR___Lab_3___Part1_marking_info[2].value = marking->p_6;
    CSR___Lab_3___Part1_marking_info[3].value = marking->p_8;
    CSR___Lab_3___Part1_marking_info[4].value = marking->p_9;
    CSR___Lab_3___Part1_marking_info[5].value = marking->p_34_4;
    CSR___Lab_3___Part1_marking_info[6].value = marking->p_34_5;
    CSR___Lab_3___Part1_marking_info[7].value = marking->p_34_6;
    CSR___Lab_3___Part1_marking_info[8].value = marking->p_34_8;
    CSR___Lab_3___Part1_marking_info[9].value = marking->p_34_9;
    CSR___Lab_3___Part1_marking_info[10].value = marking->p_36_4;
    CSR___Lab_3___Part1_marking_info[11].value = marking->p_36_5;
    CSR___Lab_3___Part1_marking_info[12].value = marking->p_36_6;
    CSR___Lab_3___Part1_marking_info[13].value = marking->p_36_8;
    CSR___Lab_3___Part1_marking_info[14].value = marking->p_36_9;
    CSR___Lab_3___Part1_marking_info[15].value = marking->p_43;
    CSR___Lab_3___Part1_marking_info[16].value = marking->p_46;
    CSR___Lab_3___Part1_marking_info[17].value = marking->p_49;
    CSR___Lab_3___Part1_marking_info[18].value = marking->p_52;
    CSR___Lab_3___Part1_marking_info[19].value = marking->p_55;
    CSR___Lab_3___Part1_marking_info[20].value = marking->p_58;
    CSR___Lab_3___Part1_marking_info[21].value = marking->p_61;
    return CSR___Lab_3___Part1_marking_info;
}

void force_CSR___Lab_3___Part1_Inputs( iopt_param_info fv[],
        CSR___Lab_3___Part1_InputSignals* in )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, CSR___Lab_3___Part1_input_info[0].name ) == 0 )
           in->outi = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_input_info[1].name ) == 0 )
           in->ini = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_input_info[2].name ) == 0 )
           in->outi_2 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_input_info[3].name ) == 0 )
           in->ini_2 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_input_info[4].name ) == 0 )
           in->outi_3 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_input_info[5].name ) == 0 )
           in->ini_3 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_input_info[6].name ) == 0 )
           in->in1 = fv[i].value;
    }
}

void force_CSR___Lab_3___Part1_Outputs( iopt_param_info fv[],
        CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
        CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, CSR___Lab_3___Part1_output_info[0].name ) == 0 )
           place_out->movei = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_output_info[1].name ) == 0 )
           place_out->movei_2 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_output_info[2].name ) == 0 )
           place_out->movei_3 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_output_info[3].name ) == 0 )
           place_out->Bot1 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_output_info[4].name ) == 0 )
           place_out->Bot2 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_output_info[5].name ) == 0 )
           place_out->Bot3 = fv[i].value;
    }
}

void force_CSR___Lab_3___Part1_Marking( iopt_param_info fv[],
        CSR___Lab_3___Part1_NetMarking* m )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[0].name ) == 0 )
           m->p_4 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[1].name ) == 0 )
           m->p_5 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[2].name ) == 0 )
           m->p_6 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[3].name ) == 0 )
           m->p_8 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[4].name ) == 0 )
           m->p_9 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[5].name ) == 0 )
           m->p_34_4 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[6].name ) == 0 )
           m->p_34_5 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[7].name ) == 0 )
           m->p_34_6 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[8].name ) == 0 )
           m->p_34_8 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[9].name ) == 0 )
           m->p_34_9 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[10].name ) == 0 )
           m->p_36_4 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[11].name ) == 0 )
           m->p_36_5 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[12].name ) == 0 )
           m->p_36_6 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[13].name ) == 0 )
           m->p_36_8 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[14].name ) == 0 )
           m->p_36_9 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[15].name ) == 0 )
           m->p_43 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[16].name ) == 0 )
           m->p_46 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[17].name ) == 0 )
           m->p_49 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[18].name ) == 0 )
           m->p_52 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[19].name ) == 0 )
           m->p_55 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[20].name ) == 0 )
           m->p_58 = fv[i].value;
        else if( strcmp( fv[i].name, CSR___Lab_3___Part1_marking_info[21].name ) == 0 )
           m->p_61 = fv[i].value;
    }
}

iopt_param_info* get_CSR___Lab_3___Part1_TFiredInfo()
{
    CSR___Lab_3___Part1_TransitionFiring* tfired = get_CSR___Lab_3___Part1_TransitionFiring();
    CSR___Lab_3___Part1_tfired_info[0].value = tfired->t_10;
    CSR___Lab_3___Part1_tfired_info[1].value = tfired->t_11;
    CSR___Lab_3___Part1_tfired_info[2].value = tfired->t_12;
    CSR___Lab_3___Part1_tfired_info[3].value = tfired->t_13;
    CSR___Lab_3___Part1_tfired_info[4].value = tfired->t_25;
    CSR___Lab_3___Part1_tfired_info[5].value = tfired->t_34_10;
    CSR___Lab_3___Part1_tfired_info[6].value = tfired->t_34_11;
    CSR___Lab_3___Part1_tfired_info[7].value = tfired->t_34_12;
    CSR___Lab_3___Part1_tfired_info[8].value = tfired->t_34_13;
    CSR___Lab_3___Part1_tfired_info[9].value = tfired->t_34_25;
    CSR___Lab_3___Part1_tfired_info[10].value = tfired->t_36_10;
    CSR___Lab_3___Part1_tfired_info[11].value = tfired->t_36_11;
    CSR___Lab_3___Part1_tfired_info[12].value = tfired->t_36_12;
    CSR___Lab_3___Part1_tfired_info[13].value = tfired->t_36_13;
    CSR___Lab_3___Part1_tfired_info[14].value = tfired->t_36_25;
    CSR___Lab_3___Part1_tfired_info[15].value = tfired->t_39;
    return CSR___Lab_3___Part1_tfired_info;
}

#endif
