-- Net CSR___Lab_3___Part1 - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2015 


Library IEEE;
Use IEEE.STD_LOGIC_1164.ALL;
Use IEEE.STD_LOGIC_ARITH.ALL;
Use IEEE.STD_LOGIC_UNSIGNED.ALL;


Entity CSR___Lab_3___Part1_main IS
Port(
    Clk : IN STD_LOGIC;
    Enable : IN STD_LOGIC;
    Reset : IN STD_LOGIC
);
End CSR___Lab_3___Part1_main;



Architecture Structural OF CSR___Lab_3___Part1_main IS

  -- Component Definition:
  Component CSR___Lab_3___Part1 IS
  Port(
      Clk : IN STD_LOGIC;
      outi : IN STD_LOGIC;
      ini : IN STD_LOGIC;
      outi_2 : IN STD_LOGIC;
      ini_2 : IN STD_LOGIC;
      outi_3 : IN STD_LOGIC;
      ini_3 : IN STD_LOGIC;
      in1 : IN STD_LOGIC;
      movei : OUT STD_LOGIC;
      movei_2 : OUT STD_LOGIC;
      movei_3 : OUT STD_LOGIC;
      Bot1 : OUT STD_LOGIC;
      Bot2 : OUT STD_LOGIC;
      Bot3 : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component CSR___Lab_3___Part1;

  -- Internal signals:

BEGIN

    U_CSR___Lab_3___Part1 : CSR___Lab_3___Part1 Port Map(
        Clk => Clk,
        outi => '0',
        ini => '0',
        outi_2 => '0',
        ini_2 => '0',
        outi_3 => '0',
        ini_3 => '0',
        in1 => '0',
         -- movei => ,
         -- movei_2 => ,
         -- movei_3 => ,
         -- Bot1 => ,
         -- Bot2 => ,
         -- Bot3 => ,
        Enable => Enable,
        Reset => Reset
    );

End Structural;
