-- Net CSR___Lab2___Part1 - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2014 




  -- Component Definition:
  Component CSR___Lab2___Part1 IS
  Port(
      Clk : IN STD_LOGIC;
      a : IN STD_LOGIC;
      b : IN STD_LOGIC;
      c : IN STD_LOGIC;
      d : IN STD_LOGIC;
      e : IN STD_LOGIC;
      k : OUT STD_LOGIC;
      l : OUT STD_LOGIC;
      m : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component CSR___Lab2___Part1;



    -- Port Map Template:
    U_CSR___Lab2___Part1 : CSR___Lab2___Part1 Port Map(
        Clk => clk,
        a => a,
        b => b,
        c => c,
        d => d,
        e => e,
        k => k,
        l => l,
        m => m,
        Enable => enable,
        Reset => reset
    );

