/* Net CSR___Lab_3___Part1 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#ifndef __CSR___Lab_3___Part1_DEFS
#define __CSR___Lab_3___Part1_DEFS


//#define HTTP_SERVER

#define TRACE_CONT_RUN       (-1)
#define TRACE_PAUSE          0
#define TRACE_SINGLE_STEP    1
#define TRACE_N_STEPS(n)     (n)

#define MODEL_NAME		CSR___Lab_3___Part1
#define MODEL_NAME_STR		"CSR___Lab_3___Part1"
#define MODEL_VERSION		"2025-10-21 16:12:49"
#define MODEL_N_INPUTS		7
#define MODEL_N_OUTPUTS		6
#define MODEL_N_PLACES		22
#define MODEL_N_TRANSITIONS	16

#ifdef __cplusplus
extern "C" {
#endif

extern int trace_control;

typedef struct {
    unsigned int p_4: 2; /* Place pl_4 */
    unsigned int p_5: 2; /* Place pl_5 */
    unsigned int p_6: 2; /* Place pl_6 */
    unsigned int p_8: 2; /* Place pl_8 */
    unsigned int p_9: 2; /* Place pl_9 */
    unsigned int p_34_4: 2; /* Place pl_4_2 */
    unsigned int p_34_5: 2; /* Place pl_5_2 */
    unsigned int p_34_6: 2; /* Place pl_6_2 */
    unsigned int p_34_8: 2; /* Place pl_8_2 */
    unsigned int p_34_9: 2; /* Place pl_9_2 */
    unsigned int p_36_4: 2; /* Place pl_4_3 */
    unsigned int p_36_5: 2; /* Place pl_5_3 */
    unsigned int p_36_6: 2; /* Place pl_6_3 */
    unsigned int p_36_8: 2; /* Place pl_8_3 */
    unsigned int p_36_9: 2; /* Place pl_9_3 */
    unsigned int p_43: 2; /* Place pl_37 */
    unsigned int p_46: 2; /* Place pl_38 */
    unsigned int p_49: 2; /* Place ppb */
    unsigned int p_52: 2; /* Place pl_32 */
    unsigned int p_55: 2; /* Place pl_32_2 */
    unsigned int p_58: 2; /* Place ppb_2 */
    unsigned int p_61: 2; /* Place ppb_3 */
    unsigned int padding: 4;
} CSR___Lab_3___Part1_NetMarking;


typedef struct {
    unsigned int outi : 1;
    unsigned int ini : 1;
    unsigned int outi_2 : 1;
    unsigned int ini_2 : 1;
    unsigned int outi_3 : 1;
    unsigned int ini_3 : 1;
    unsigned int in1 : 1;
} CSR___Lab_3___Part1_InputSignals;


typedef struct {
} CSR___Lab_3___Part1_InputSignalEvents;


typedef struct {
} CSR___Lab_3___Part1_OutputSignalEvents;


typedef struct {
    unsigned int movei : 1;
    unsigned int movei_2 : 1;
    unsigned int movei_3 : 1;
    unsigned int Bot1 : 1;
    unsigned int Bot2 : 1;
    unsigned int Bot3 : 1;
} CSR___Lab_3___Part1_PlaceOutputSignals;


typedef struct {
} CSR___Lab_3___Part1_EventOutputSignals;


typedef struct {
    unsigned int t_10 : 1; /* tr_10 */
    unsigned int t_11 : 1; /* tr_11 */
    unsigned int t_12 : 1; /* tr_12 */
    unsigned int t_13 : 1; /* tr_13 */
    unsigned int t_25 : 1; /* tr_25 */
    unsigned int t_34_10 : 1; /* tr_10_2 */
    unsigned int t_34_11 : 1; /* tr_11_2 */
    unsigned int t_34_12 : 1; /* tr_12_2 */
    unsigned int t_34_13 : 1; /* tr_13_2 */
    unsigned int t_34_25 : 1; /* tr_25_2 */
    unsigned int t_36_10 : 1; /* tr_10_3 */
    unsigned int t_36_11 : 1; /* tr_11_3 */
    unsigned int t_36_12 : 1; /* tr_12_3 */
    unsigned int t_36_13 : 1; /* tr_13_3 */
    unsigned int t_36_25 : 1; /* tr_25_3 */
    unsigned int t_39 : 1; /* tr_39 */
    unsigned int count: 8;
} CSR___Lab_3___Part1_TransitionFiring;

/* Array declarations: */


/* Runtime text info: */
typedef struct {
#ifdef __cplusplus
    const
#endif
    char* name;
    int value;
} iopt_param_info;

extern iopt_param_info* get_CSR___Lab_3___Part1_InputInfo();
extern iopt_param_info* get_CSR___Lab_3___Part1_OutputInfo();
extern iopt_param_info* get_CSR___Lab_3___Part1_MarkingInfo();
extern iopt_param_info* get_CSR___Lab_3___Part1_TFiredInfo();
extern void force_CSR___Lab_3___Part1_Inputs( iopt_param_info fv[], CSR___Lab_3___Part1_InputSignals* in );
extern void force_CSR___Lab_3___Part1_Outputs( iopt_param_info fv[], CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void force_CSR___Lab_3___Part1_Marking( iopt_param_info fv[], CSR___Lab_3___Part1_NetMarking* m );


extern void createInitial_CSR___Lab_3___Part1_NetMarking( CSR___Lab_3___Part1_NetMarking* init_marking );
extern void createEmpty_CSR___Lab_3___Part1_NetMarking( CSR___Lab_3___Part1_NetMarking* empty_marking );
extern void add_CSR___Lab_3___Part1_NetMarkings( CSR___Lab_3___Part1_NetMarking* dest_marking, CSR___Lab_3___Part1_NetMarking* source_marking );

extern void init_CSR___Lab_3___Part1_OutputSignals( CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );

/* Transition 10 - tr_10 */
extern int  t_10_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_10_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_10_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_10_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_10_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_10_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 11 - tr_11 */
extern int  t_11_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_11_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_11_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_11_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_11_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_11_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 12 - tr_12 */
extern int  t_12_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_12_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_12_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_12_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_12_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_12_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 13 - tr_13 */
extern int  t_13_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_13_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_13_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_13_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_13_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_13_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 25 - tr_25 */
extern int  t_25_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_25_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_25_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_25_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_25_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_25_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 34_10 - tr_10_2 */
extern int  t_34_10_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_34_10_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_34_10_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_34_10_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_10_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_10_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 34_11 - tr_11_2 */
extern int  t_34_11_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_34_11_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_34_11_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_34_11_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_11_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_11_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 34_12 - tr_12_2 */
extern int  t_34_12_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_34_12_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_34_12_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_34_12_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_12_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_12_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 34_13 - tr_13_2 */
extern int  t_34_13_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_34_13_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_34_13_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_34_13_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_13_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_13_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 34_25 - tr_25_2 */
extern int  t_34_25_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_34_25_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_34_25_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_34_25_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_25_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_34_25_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 36_10 - tr_10_3 */
extern int  t_36_10_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_36_10_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_36_10_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_36_10_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_10_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_10_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 36_11 - tr_11_3 */
extern int  t_36_11_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_36_11_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_36_11_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_36_11_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_11_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_11_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 36_12 - tr_12_3 */
extern int  t_36_12_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_36_12_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_36_12_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_36_12_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_12_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_12_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 36_13 - tr_13_3 */
extern int  t_36_13_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_36_13_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_36_13_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_36_13_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_13_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_13_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 36_25 - tr_25_3 */
extern int  t_36_25_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_36_25_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_36_25_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_36_25_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_25_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_36_25_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
/* Transition 39 - tr_39 */
extern int  t_39_enabled( CSR___Lab_3___Part1_NetMarking* prev, CSR___Lab_3___Part1_NetMarking* avail );
extern int  t_39_events( CSR___Lab_3___Part1_InputSignalEvents* events );
extern int  t_39_guards( CSR___Lab_3___Part1_NetMarking* marking, CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* ev_out );
extern void t_39_remove_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_39_add_marks( CSR___Lab_3___Part1_NetMarking* marking );
extern void t_39_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out );
extern void CSR___Lab_3___Part1_GenerateInputSignalEvents( CSR___Lab_3___Part1_InputSignals *old_values, CSR___Lab_3___Part1_InputSignals *new_values, CSR___Lab_3___Part1_InputSignalEvents *events );

extern void CSR___Lab_3___Part1_GenerateEventOutputSignals( CSR___Lab_3___Part1_OutputSignalEvents *events, CSR___Lab_3___Part1_EventOutputSignals *signals );

extern void CSR___Lab_3___Part1_GenerateTransitionActionOutputSignals( CSR___Lab_3___Part1_TransitionFiring *tfired, CSR___Lab_3___Part1_NetMarking *marking, CSR___Lab_3___Part1_EventOutputSignals *signals );

extern void CSR___Lab_3___Part1_GeneratePlaceOutputSignals( CSR___Lab_3___Part1_NetMarking *marking, CSR___Lab_3___Part1_InputSignals *inputs, CSR___Lab_3___Part1_PlaceOutputSignals *place_out, CSR___Lab_3___Part1_EventOutputSignals *ev_out );

extern void CSR___Lab_3___Part1_ExecutionStep( CSR___Lab_3___Part1_NetMarking *prev_marking, CSR___Lab_3___Part1_InputSignals *inputs, CSR___Lab_3___Part1_InputSignals *prev_in, CSR___Lab_3___Part1_PlaceOutputSignals *place_out, CSR___Lab_3___Part1_EventOutputSignals *ev_out );

extern void CSR___Lab_3___Part1_InitializeIO();
extern void CSR___Lab_3___Part1_GetInputSignals( CSR___Lab_3___Part1_InputSignals* inputs, CSR___Lab_3___Part1_InputSignalEvents* events );
extern void CSR___Lab_3___Part1_PutOutputSignals( CSR___Lab_3___Part1_PlaceOutputSignals* place_out, CSR___Lab_3___Part1_EventOutputSignals* event_out, CSR___Lab_3___Part1_OutputSignalEvents* events );
extern void CSR___Lab_3___Part1_LoopDelay();
extern int CSR___Lab_3___Part1_FinishExecution( CSR___Lab_3___Part1_NetMarking* marking );

extern CSR___Lab_3___Part1_NetMarking* get_CSR___Lab_3___Part1_NetMarking();
extern CSR___Lab_3___Part1_InputSignals* get_CSR___Lab_3___Part1_InputSignals();
extern CSR___Lab_3___Part1_PlaceOutputSignals* get_CSR___Lab_3___Part1_PlaceOutputSignals();
extern CSR___Lab_3___Part1_EventOutputSignals* get_CSR___Lab_3___Part1_EventOutputSignals();
extern CSR___Lab_3___Part1_TransitionFiring* get_CSR___Lab_3___Part1_TransitionFiring();

#ifdef __cplusplus
};
#endif


#endif
