/* Net CSR___Lab_3___Part1 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */
/* Please fill the necessary code to perform hardware IO. */


#include <stdlib.h>
#include "net_types.h"


#ifdef ARDUINO
#include <Arduino.h>
#define ANALOG_IN_MAX  1023
#define ANALOG_OUT_MAX 255
#else
#define INPUT    0
#define OUTPUT   1
#define ANALOG_IN_MAX  1023
#define ANALOG_OUT_MAX 1023
extern void pinMode( int, int );
extern int  digitalRead( int );
extern void digitalWrite( int, int );
extern int  analogRead( int );
extern void analogWrite( int, int );
#endif


// Remote IcE/Debug forced values:
#ifdef HTTP_SERVER
iopt_param_info *input_fv = NULL, *output_fv = NULL;
#endif


/* Executed just once, before net execution starts: */
void CSR___Lab_3___Part1_InitializeIO()
{
    pinMode( 33, INPUT ); /* outi */
    pinMode( 35, INPUT ); /* ini */
    pinMode( 37, INPUT ); /* outi_2 */
    pinMode( 39, INPUT ); /* ini_2 */
    pinMode( 41, INPUT ); /* outi_3 */
    pinMode( 43, INPUT ); /* ini_3 */
    pinMode( 31, INPUT ); /* in1 */

    pinMode( 28, OUTPUT ); /* movei */
    pinMode( 30, OUTPUT ); /* movei_2 */
    pinMode( 32, OUTPUT ); /* movei_3 */
    pinMode( 34, OUTPUT ); /* Bot1 */
    pinMode( 36, OUTPUT ); /* Bot2 */
    pinMode( 38, OUTPUT ); /* Bot3 */
}



/* Read all hardware input signals and fill data-structure */
void CSR___Lab_3___Part1_GetInputSignals(
            CSR___Lab_3___Part1_InputSignals* inputs,
            CSR___Lab_3___Part1_InputSignalEvents* events )
{
    inputs->outi   = digitalRead(33);
    inputs->ini    = digitalRead(35);
    inputs->outi_2 = digitalRead(37);
    inputs->ini_2  = digitalRead(39);
    inputs->outi_3 = digitalRead(41);
    inputs->ini_3  = digitalRead(43);
    inputs->in1    = digitalRead(31);

#ifdef HTTP_SERVER
    if( input_fv != NULL )
        force_CSR___Lab_3___Part1_Inputs( input_fv, inputs );
#endif
}



/* Write all output values to physical hardware outputs */
void CSR___Lab_3___Part1_PutOutputSignals(
            CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
            CSR___Lab_3___Part1_EventOutputSignals* event_out,
            CSR___Lab_3___Part1_OutputSignalEvents* events )
{
#ifdef HTTP_SERVER
    if( output_fv != NULL )
        force_CSR___Lab_3___Part1_Outputs( output_fv, place_out, event_out );
#endif

    digitalWrite(28, place_out->movei);
    digitalWrite(30, place_out->movei_2);
    digitalWrite(32, place_out->movei_3);
    digitalWrite(34, place_out->Bot1);
    digitalWrite(36, place_out->Bot2);
    digitalWrite(38, place_out->Bot3);
}



/* Delay between loop iterations to save CPU and power consumption */
void CSR___Lab_3___Part1_LoopDelay()
{
}

/* Must return 1 to finish net execution */
int CSR___Lab_3___Part1_FinishExecution( CSR___Lab_3___Part1_NetMarking* marking )
{
    return 0;
}



