/* Net CSR___Lab_3___Part1 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include <string.h>
#include "net_types.h"


static CSR___Lab_3___Part1_TransitionFiring tfired;
    

void CSR___Lab_3___Part1_ExecutionStep(
     CSR___Lab_3___Part1_NetMarking *prev_marking,
     CSR___Lab_3___Part1_InputSignals *inputs,
     CSR___Lab_3___Part1_InputSignals *prev_in,
     CSR___Lab_3___Part1_PlaceOutputSignals *place_out,
     CSR___Lab_3___Part1_EventOutputSignals *ev_out )
{
    CSR___Lab_3___Part1_NetMarking add_marking;
    CSR___Lab_3___Part1_NetMarking avail_marking = *prev_marking;
    CSR___Lab_3___Part1_InputSignalEvents input_events;
    CSR___Lab_3___Part1_OutputSignalEvents output_events;

    memset( &output_events, 0, sizeof(output_events) );
    memset( &tfired, 0, sizeof(tfired) );

    createEmpty_CSR___Lab_3___Part1_NetMarking( &add_marking );
    CSR___Lab_3___Part1_GetInputSignals( inputs, &input_events );
    CSR___Lab_3___Part1_GenerateInputSignalEvents( prev_in, inputs, &input_events );
    *prev_in = *inputs;

    /* Transition tr_10 */
    if( t_10_enabled( prev_marking, &avail_marking ) &&
        t_10_events( &input_events ) &&
        t_10_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_10 = 1;
        t_10_remove_marks( &avail_marking );
        t_10_add_marks( &add_marking );
        t_10_generate_output_events( &output_events );
    }

    /* Transition tr_11 */
    if( t_11_enabled( prev_marking, &avail_marking ) &&
        t_11_events( &input_events ) &&
        t_11_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_11 = 1;
        t_11_remove_marks( &avail_marking );
        t_11_add_marks( &add_marking );
        t_11_generate_output_events( &output_events );
    }

    /* Transition tr_12 */
    if( t_12_enabled( prev_marking, &avail_marking ) &&
        t_12_events( &input_events ) &&
        t_12_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_12 = 1;
        t_12_remove_marks( &avail_marking );
        t_12_add_marks( &add_marking );
        t_12_generate_output_events( &output_events );
    }

    /* Transition tr_13 */
    if( t_13_enabled( prev_marking, &avail_marking ) &&
        t_13_events( &input_events ) &&
        t_13_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_13 = 1;
        t_13_remove_marks( &avail_marking );
        t_13_add_marks( &add_marking );
        t_13_generate_output_events( &output_events );
    }

    /* Transition tr_25 */
    if( t_25_enabled( prev_marking, &avail_marking ) &&
        t_25_events( &input_events ) &&
        t_25_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_25 = 1;
        t_25_remove_marks( &avail_marking );
        t_25_add_marks( &add_marking );
        t_25_generate_output_events( &output_events );
    }

    /* Transition tr_10_2 */
    if( t_34_10_enabled( prev_marking, &avail_marking ) &&
        t_34_10_events( &input_events ) &&
        t_34_10_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_34_10 = 1;
        t_34_10_remove_marks( &avail_marking );
        t_34_10_add_marks( &add_marking );
        t_34_10_generate_output_events( &output_events );
    }

    /* Transition tr_11_2 */
    if( t_34_11_enabled( prev_marking, &avail_marking ) &&
        t_34_11_events( &input_events ) &&
        t_34_11_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_34_11 = 1;
        t_34_11_remove_marks( &avail_marking );
        t_34_11_add_marks( &add_marking );
        t_34_11_generate_output_events( &output_events );
    }

    /* Transition tr_12_2 */
    if( t_34_12_enabled( prev_marking, &avail_marking ) &&
        t_34_12_events( &input_events ) &&
        t_34_12_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_34_12 = 1;
        t_34_12_remove_marks( &avail_marking );
        t_34_12_add_marks( &add_marking );
        t_34_12_generate_output_events( &output_events );
    }

    /* Transition tr_13_2 */
    if( t_34_13_enabled( prev_marking, &avail_marking ) &&
        t_34_13_events( &input_events ) &&
        t_34_13_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_34_13 = 1;
        t_34_13_remove_marks( &avail_marking );
        t_34_13_add_marks( &add_marking );
        t_34_13_generate_output_events( &output_events );
    }

    /* Transition tr_25_2 */
    if( t_34_25_enabled( prev_marking, &avail_marking ) &&
        t_34_25_events( &input_events ) &&
        t_34_25_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_34_25 = 1;
        t_34_25_remove_marks( &avail_marking );
        t_34_25_add_marks( &add_marking );
        t_34_25_generate_output_events( &output_events );
    }

    /* Transition tr_10_3 */
    if( t_36_10_enabled( prev_marking, &avail_marking ) &&
        t_36_10_events( &input_events ) &&
        t_36_10_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_36_10 = 1;
        t_36_10_remove_marks( &avail_marking );
        t_36_10_add_marks( &add_marking );
        t_36_10_generate_output_events( &output_events );
    }

    /* Transition tr_11_3 */
    if( t_36_11_enabled( prev_marking, &avail_marking ) &&
        t_36_11_events( &input_events ) &&
        t_36_11_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_36_11 = 1;
        t_36_11_remove_marks( &avail_marking );
        t_36_11_add_marks( &add_marking );
        t_36_11_generate_output_events( &output_events );
    }

    /* Transition tr_12_3 */
    if( t_36_12_enabled( prev_marking, &avail_marking ) &&
        t_36_12_events( &input_events ) &&
        t_36_12_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_36_12 = 1;
        t_36_12_remove_marks( &avail_marking );
        t_36_12_add_marks( &add_marking );
        t_36_12_generate_output_events( &output_events );
    }

    /* Transition tr_13_3 */
    if( t_36_13_enabled( prev_marking, &avail_marking ) &&
        t_36_13_events( &input_events ) &&
        t_36_13_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_36_13 = 1;
        t_36_13_remove_marks( &avail_marking );
        t_36_13_add_marks( &add_marking );
        t_36_13_generate_output_events( &output_events );
    }

    /* Transition tr_25_3 */
    if( t_36_25_enabled( prev_marking, &avail_marking ) &&
        t_36_25_events( &input_events ) &&
        t_36_25_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_36_25 = 1;
        t_36_25_remove_marks( &avail_marking );
        t_36_25_add_marks( &add_marking );
        t_36_25_generate_output_events( &output_events );
    }

    /* Transition tr_39 */
    if( t_39_enabled( prev_marking, &avail_marking ) &&
        t_39_events( &input_events ) &&
        t_39_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_39 = 1;
        t_39_remove_marks( &avail_marking );
        t_39_add_marks( &add_marking );
        t_39_generate_output_events( &output_events );
    }

    add_CSR___Lab_3___Part1_NetMarkings( &avail_marking, &add_marking );

    CSR___Lab_3___Part1_GenerateTransitionActionOutputSignals( &tfired, &avail_marking, ev_out );
    CSR___Lab_3___Part1_GeneratePlaceOutputSignals( &avail_marking, inputs, place_out, ev_out );
    CSR___Lab_3___Part1_GenerateEventOutputSignals( &output_events, ev_out );
    CSR___Lab_3___Part1_PutOutputSignals( place_out, ev_out, &output_events );
    *prev_marking = avail_marking;
}

CSR___Lab_3___Part1_TransitionFiring* get_CSR___Lab_3___Part1_TransitionFiring()
{
    return &tfired;
}

