/* Net CSR___Lab_3___Part1 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include "net_types.h"


int trace_control = TRACE_CONT_RUN;

extern void httpServer_init();
extern void httpServer_getRequest();
extern void httpServer_sendResponse();
extern void httpServer_disconnectClient();
extern void httpServer_checkBreakPoints();
extern void httpServer_finish();

static CSR___Lab_3___Part1_NetMarking marking;
static CSR___Lab_3___Part1_InputSignals inputs, prev_inputs;
static CSR___Lab_3___Part1_PlaceOutputSignals place_out;
static CSR___Lab_3___Part1_EventOutputSignals ev_out;

void setup()
{
    createInitial_CSR___Lab_3___Part1_NetMarking( &marking );
    init_CSR___Lab_3___Part1_OutputSignals( &place_out, &ev_out );
    CSR___Lab_3___Part1_InitializeIO();
    CSR___Lab_3___Part1_GetInputSignals( &prev_inputs, NULL );
#ifdef HTTP_SERVER
    httpServer_init();
#endif
}

void loop()
{
#ifdef HTTP_SERVER
    httpServer_getRequest();
#endif

    if( trace_control != TRACE_PAUSE )
        CSR___Lab_3___Part1_ExecutionStep( &marking, &inputs, &prev_inputs, &place_out, &ev_out );
    else CSR___Lab_3___Part1_GetInputSignals( &inputs, NULL );
    if( trace_control > TRACE_PAUSE ) --trace_control;

#ifdef HTTP_SERVER
    httpServer_sendResponse();
#endif

    CSR___Lab_3___Part1_LoopDelay();

#ifdef HTTP_SERVER
    httpServer_disconnectClient();
    httpServer_checkBreakPoints();
#endif
}

#ifndef ARDUINO
int main()
{
    setup();

    do loop();
    while( CSR___Lab_3___Part1_FinishExecution( &marking ) == 0 );

#ifdef HTTP_SERVER
    httpServer_finish();
#endif

    return 0;
}
#endif


CSR___Lab_3___Part1_NetMarking* get_CSR___Lab_3___Part1_NetMarking()
{
    return &marking;
}

CSR___Lab_3___Part1_InputSignals* get_CSR___Lab_3___Part1_InputSignals()
{
    return &inputs;
}

CSR___Lab_3___Part1_PlaceOutputSignals* get_CSR___Lab_3___Part1_PlaceOutputSignals()
{
    return &place_out;
}

CSR___Lab_3___Part1_EventOutputSignals* get_CSR___Lab_3___Part1_EventOutputSignals()
{
    return &ev_out;
}

