/* Net CSR___Lab_3___Part1 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include "net_types.h"


#define ABS(x) (((x)>=0)?(x):-(x))


/* Array implementation: */


void createInitial_CSR___Lab_3___Part1_NetMarking( CSR___Lab_3___Part1_NetMarking* init_marking )
{
    memset( init_marking, 0, sizeof(*init_marking) );
    init_marking->p_4 = 0; /* Place pl_4 */
    init_marking->p_5 = 1; /* Place pl_5 */
    init_marking->p_6 = 0; /* Place pl_6 */
    init_marking->p_8 = 0; /* Place pl_8 */
    init_marking->p_9 = 0; /* Place pl_9 */
    init_marking->p_34_4 = 0; /* Place pl_4_2 */
    init_marking->p_34_5 = 1; /* Place pl_5_2 */
    init_marking->p_34_6 = 0; /* Place pl_6_2 */
    init_marking->p_34_8 = 0; /* Place pl_8_2 */
    init_marking->p_34_9 = 0; /* Place pl_9_2 */
    init_marking->p_36_4 = 0; /* Place pl_4_3 */
    init_marking->p_36_5 = 1; /* Place pl_5_3 */
    init_marking->p_36_6 = 0; /* Place pl_6_3 */
    init_marking->p_36_8 = 0; /* Place pl_8_3 */
    init_marking->p_36_9 = 0; /* Place pl_9_3 */
    init_marking->p_43 = 1; /* Place pl_37 */
    init_marking->p_46 = 0; /* Place pl_38 */
    init_marking->p_49 = 0; /* Place ppb */
    init_marking->p_52 = 1; /* Place pl_32 */
    init_marking->p_55 = 1; /* Place pl_32_2 */
    init_marking->p_58 = 0; /* Place ppb_2 */
    init_marking->p_61 = 1; /* Place ppb_3 */
}

void createEmpty_CSR___Lab_3___Part1_NetMarking( CSR___Lab_3___Part1_NetMarking* empty_marking )
{
    empty_marking->p_4 = 0; /* Place pl_4 */
    empty_marking->p_5 = 0; /* Place pl_5 */
    empty_marking->p_6 = 0; /* Place pl_6 */
    empty_marking->p_8 = 0; /* Place pl_8 */
    empty_marking->p_9 = 0; /* Place pl_9 */
    empty_marking->p_34_4 = 0; /* Place pl_4_2 */
    empty_marking->p_34_5 = 0; /* Place pl_5_2 */
    empty_marking->p_34_6 = 0; /* Place pl_6_2 */
    empty_marking->p_34_8 = 0; /* Place pl_8_2 */
    empty_marking->p_34_9 = 0; /* Place pl_9_2 */
    empty_marking->p_36_4 = 0; /* Place pl_4_3 */
    empty_marking->p_36_5 = 0; /* Place pl_5_3 */
    empty_marking->p_36_6 = 0; /* Place pl_6_3 */
    empty_marking->p_36_8 = 0; /* Place pl_8_3 */
    empty_marking->p_36_9 = 0; /* Place pl_9_3 */
    empty_marking->p_43 = 0; /* Place pl_37 */
    empty_marking->p_46 = 0; /* Place pl_38 */
    empty_marking->p_49 = 0; /* Place ppb */
    empty_marking->p_52 = 0; /* Place pl_32 */
    empty_marking->p_55 = 0; /* Place pl_32_2 */
    empty_marking->p_58 = 0; /* Place ppb_2 */
    empty_marking->p_61 = 0; /* Place ppb_3 */
}

void add_CSR___Lab_3___Part1_NetMarkings(
    CSR___Lab_3___Part1_NetMarking* dest_marking,
    CSR___Lab_3___Part1_NetMarking* source_marking )
{
    dest_marking->p_4 += source_marking->p_4; /* Place pl_4 */
    dest_marking->p_5 += source_marking->p_5; /* Place pl_5 */
    dest_marking->p_6 += source_marking->p_6; /* Place pl_6 */
    dest_marking->p_8 += source_marking->p_8; /* Place pl_8 */
    dest_marking->p_9 += source_marking->p_9; /* Place pl_9 */
    dest_marking->p_34_4 += source_marking->p_34_4; /* Place pl_4_2 */
    dest_marking->p_34_5 += source_marking->p_34_5; /* Place pl_5_2 */
    dest_marking->p_34_6 += source_marking->p_34_6; /* Place pl_6_2 */
    dest_marking->p_34_8 += source_marking->p_34_8; /* Place pl_8_2 */
    dest_marking->p_34_9 += source_marking->p_34_9; /* Place pl_9_2 */
    dest_marking->p_36_4 += source_marking->p_36_4; /* Place pl_4_3 */
    dest_marking->p_36_5 += source_marking->p_36_5; /* Place pl_5_3 */
    dest_marking->p_36_6 += source_marking->p_36_6; /* Place pl_6_3 */
    dest_marking->p_36_8 += source_marking->p_36_8; /* Place pl_8_3 */
    dest_marking->p_36_9 += source_marking->p_36_9; /* Place pl_9_3 */
    dest_marking->p_43 += source_marking->p_43; /* Place pl_37 */
    dest_marking->p_46 += source_marking->p_46; /* Place pl_38 */
    dest_marking->p_49 += source_marking->p_49; /* Place ppb */
    dest_marking->p_52 += source_marking->p_52; /* Place pl_32 */
    dest_marking->p_55 += source_marking->p_55; /* Place pl_32_2 */
    dest_marking->p_58 += source_marking->p_58; /* Place ppb_2 */
    dest_marking->p_61 += source_marking->p_61; /* Place ppb_3 */
}

void init_CSR___Lab_3___Part1_OutputSignals(
    CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
    CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    memset( place_out, 0, sizeof(*place_out) );
    memset( ev_out, 0, sizeof(*ev_out) );
    place_out->movei = 0;
    place_out->movei_2 = 0;
    place_out->movei_3 = 0;
    place_out->Bot1 = 0;
    place_out->Bot2 = 0;
    place_out->Bot3 = 0;
}

/* Transition 10 - tr_10 */
int t_10_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_46 >= 1 );
}

int t_10_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_10_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi == 1 );
}

void t_10_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_46--;
}

void t_10_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_4++;
}

void t_10_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 11 - tr_11 */
int t_11_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_4 >= 1 && avail->p_5 >= 1 );
}

int t_11_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_11_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi == 1 );
}

void t_11_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_4--;
    marking->p_5--;
}

void t_11_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_6++;
}

void t_11_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 12 - tr_12 */
int t_12_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_6 >= 1 );
}

int t_12_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_12_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi == 0 );
}

void t_12_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_6--;
}

void t_12_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_8++;
    marking->p_43++;
}

void t_12_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 13 - tr_13 */
int t_13_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_8 >= 1 && avail->p_52 >= 1 );
}

int t_13_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_13_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->ini == 1 );
}

void t_13_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_8--;
    marking->p_52--;
}

void t_13_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_9++;
}

void t_13_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 25 - tr_25 */
int t_25_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_9 >= 1 );
}

int t_25_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_25_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->ini == 1 );
}

void t_25_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_9--;
}

void t_25_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_5++;
    marking->p_49++;
}

void t_25_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 34_10 - tr_10_2 */
int t_34_10_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_49 >= 1 );
}

int t_34_10_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_34_10_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi_2 == 1 );
}

void t_34_10_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_49--;
}

void t_34_10_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_4++;
}

void t_34_10_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 34_11 - tr_11_2 */
int t_34_11_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_34_4 >= 1 && avail->p_34_5 >= 1 );
}

int t_34_11_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_34_11_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi_2 == 1 );
}

void t_34_11_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_4--;
    marking->p_34_5--;
}

void t_34_11_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_6++;
}

void t_34_11_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 34_12 - tr_12_2 */
int t_34_12_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_34_6 >= 1 );
}

int t_34_12_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_34_12_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi_2 == 0 );
}

void t_34_12_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_6--;
}

void t_34_12_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_8++;
    marking->p_52++;
}

void t_34_12_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 34_13 - tr_13_2 */
int t_34_13_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_34_8 >= 1 && avail->p_55 >= 1 );
}

int t_34_13_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_34_13_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->ini_2 == 1 );
}

void t_34_13_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_8--;
    marking->p_55--;
}

void t_34_13_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_9++;
}

void t_34_13_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 34_25 - tr_25_2 */
int t_34_25_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_34_9 >= 1 );
}

int t_34_25_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_34_25_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->ini_2 == 1 );
}

void t_34_25_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_9--;
}

void t_34_25_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_34_5++;
    marking->p_58++;
}

void t_34_25_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 36_10 - tr_10_3 */
int t_36_10_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_58 >= 1 );
}

int t_36_10_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_36_10_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi_3 == 1 );
}

void t_36_10_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_58--;
}

void t_36_10_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_4++;
}

void t_36_10_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 36_11 - tr_11_3 */
int t_36_11_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_36_4 >= 1 && avail->p_36_5 >= 1 );
}

int t_36_11_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_36_11_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi_3 == 1 );
}

void t_36_11_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_4--;
    marking->p_36_5--;
}

void t_36_11_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_6++;
}

void t_36_11_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 36_12 - tr_12_3 */
int t_36_12_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_36_6 >= 1 );
}

int t_36_12_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_36_12_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->outi_3 == 0 );
}

void t_36_12_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_6--;
}

void t_36_12_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_8++;
    marking->p_55++;
}

void t_36_12_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 36_13 - tr_13_3 */
int t_36_13_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_36_8 >= 1 && avail->p_61 >= 1 );
}

int t_36_13_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_36_13_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->ini_3 == 1 );
}

void t_36_13_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_8--;
    marking->p_61--;
}

void t_36_13_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_9++;
}

void t_36_13_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 36_25 - tr_25_3 */
int t_36_25_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_36_9 >= 1 );
}

int t_36_25_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_36_25_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->ini_3 == 1 );
}

void t_36_25_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_9--;
}

void t_36_25_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_36_5++;
    marking->p_61++;
}

void t_36_25_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Transition 39 - tr_39 */
int t_39_enabled( CSR___Lab_3___Part1_NetMarking* prev,
                    CSR___Lab_3___Part1_NetMarking* avail )
{
    return ( avail->p_43 >= 1 );
}

int t_39_events( CSR___Lab_3___Part1_InputSignalEvents* events )
{
    return (  1  );
}

int t_39_guards( CSR___Lab_3___Part1_NetMarking* marking,
                   CSR___Lab_3___Part1_InputSignals* inputs,
                   CSR___Lab_3___Part1_PlaceOutputSignals* place_out,
                   CSR___Lab_3___Part1_EventOutputSignals* ev_out )
{
    return ( inputs->in1 == 1 );
}

void t_39_remove_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_43--;
}

void t_39_add_marks( CSR___Lab_3___Part1_NetMarking* marking )
{
    marking->p_46++;
}

void t_39_generate_output_events( CSR___Lab_3___Part1_OutputSignalEvents* ev_out )
{
}


/* Input event processing: */
void CSR___Lab_3___Part1_GenerateInputSignalEvents(
        CSR___Lab_3___Part1_InputSignals *old_values,
        CSR___Lab_3___Part1_InputSignals *new_values,
        CSR___Lab_3___Part1_InputSignalEvents *events )
{
}

/* Output event processing: */
void CSR___Lab_3___Part1_GenerateEventOutputSignals(
    CSR___Lab_3___Part1_OutputSignalEvents *events,
    CSR___Lab_3___Part1_EventOutputSignals *signals )
{
}

/* Transition action processing: */
void CSR___Lab_3___Part1_GenerateTransitionActionOutputSignals(
    CSR___Lab_3___Part1_TransitionFiring *tfired,
    CSR___Lab_3___Part1_NetMarking *marking,
    CSR___Lab_3___Part1_EventOutputSignals *ev_out )
{
}

/* Place Output Processing */
void CSR___Lab_3___Part1_GeneratePlaceOutputSignals(
    CSR___Lab_3___Part1_NetMarking *marking,
    CSR___Lab_3___Part1_InputSignals *inputs,
    CSR___Lab_3___Part1_PlaceOutputSignals *place_out,
    CSR___Lab_3___Part1_EventOutputSignals *ev_out )
{
    int exp_res, new_val, n_writes;
    CSR___Lab_3___Part1_PlaceOutputSignals new_out = *place_out;
    
    /* Signal movei */
    new_val = 0;
    if( marking->p_46 > 0 ) { /* Place pl_38 */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.movei = 1;
    else if( new_val < 0 ) new_out.movei = 0;
    else new_out.movei = new_val;

    /* Signal movei_2 */
    new_val = 0;
    if( marking->p_49 > 0 ) { /* Place ppb */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.movei_2 = 1;
    else if( new_val < 0 ) new_out.movei_2 = 0;
    else new_out.movei_2 = new_val;

    /* Signal movei_3 */
    new_val = 0;
    if( marking->p_58 > 0 ) { /* Place ppb_2 */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.movei_3 = 1;
    else if( new_val < 0 ) new_out.movei_3 = 0;
    else new_out.movei_3 = new_val;

    /* Signal Bot1 */
    new_val = 0;
    if( marking->p_6 > 0 ) { /* Place pl_6 */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_8 > 0 ) { /* Place pl_8 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Bot1 = 1;
    else if( new_val < 0 ) new_out.Bot1 = 0;
    else new_out.Bot1 = new_val;

    /* Signal Bot2 */
    new_val = 0;
    if( marking->p_34_6 > 0 ) { /* Place pl_6_2 */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_34_8 > 0 ) { /* Place pl_8_2 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Bot2 = 1;
    else if( new_val < 0 ) new_out.Bot2 = 0;
    else new_out.Bot2 = new_val;

    /* Signal Bot3 */
    new_val = 0;
    if( marking->p_36_6 > 0 ) { /* Place pl_6_3 */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_36_8 > 0 ) { /* Place pl_8_3 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Bot3 = 1;
    else if( new_val < 0 ) new_out.Bot3 = 0;
    else new_out.Bot3 = new_val;

    *place_out = new_out;
}

