-- Net CSR___Lab3___Part4 - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2014 




  -- Component Definition:
  Component CSR___Lab3___Part4 IS
  Port(
      Clk : IN STD_LOGIC;
      ini : IN STD_LOGIC;
      outi : IN STD_LOGIC;
      ini_2 : IN STD_LOGIC;
      outi_2 : IN STD_LOGIC;
      ini_3 : IN STD_LOGIC;
      outi_3 : IN STD_LOGIC;
      in1 : IN STD_LOGIC;
      Bot1_i : IN STD_LOGIC;
      Bot2_i : IN STD_LOGIC;
      Bot3_i : IN STD_LOGIC;
      movei_i : IN STD_LOGIC;
      movei_2_i : IN STD_LOGIC;
      movei_3_i : IN STD_LOGIC;
      Bot1 : OUT STD_LOGIC;
      Bot2 : OUT STD_LOGIC;
      Bot3 : OUT STD_LOGIC;
      movei : OUT STD_LOGIC;
      movei_2 : OUT STD_LOGIC;
      movei_3 : OUT STD_LOGIC;
      in1_o : OUT STD_LOGIC;
      ini_o : OUT STD_LOGIC;
      outi_o : OUT STD_LOGIC;
      ini_2_o : OUT STD_LOGIC;
      outi_2_o : OUT STD_LOGIC;
      ini_3_o : OUT STD_LOGIC;
      outi_3_o : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component CSR___Lab3___Part4;



    -- Port Map Template:
    U_CSR___Lab3___Part4 : CSR___Lab3___Part4 Port Map(
        Clk => clk,
        ini => ini,
        outi => outi,
        ini_2 => ini_2,
        outi_2 => outi_2,
        ini_3 => ini_3,
        outi_3 => outi_3,
        in1 => in1,
        Bot1_i => Bot1_i,
        Bot2_i => Bot2_i,
        Bot3_i => Bot3_i,
        movei_i => movei_i,
        movei_2_i => movei_2_i,
        movei_3_i => movei_3_i,
        Bot1 => Bot1,
        Bot2 => Bot2,
        Bot3 => Bot3,
        movei => movei,
        movei_2 => movei_2,
        movei_3 => movei_3,
        in1_o => in1_o,
        ini_o => ini_o,
        outi_o => outi_o,
        ini_2_o => ini_2_o,
        outi_2_o => outi_2_o,
        ini_3_o => ini_3_o,
        outi_3_o => outi_3_o,
        Enable => enable,
        Reset => reset
    );

