-- Net CSR___Lab_3___Part1 - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2015

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

Entity CSR_Lab_3_Part1_main IS
Port(
    Clk     : IN  STD_LOGIC;
    Enable  : IN  STD_LOGIC;
    Reset   : IN  STD_LOGIC;
    ini     : IN  STD_LOGIC;
    outi    : IN  STD_LOGIC;
    ini_2   : IN  STD_LOGIC;
    outi_2  : IN  STD_LOGIC;
    ini_3   : IN  STD_LOGIC;
    outi_3  : IN  STD_LOGIC;
    in1     : IN  STD_LOGIC;
    movei   : OUT STD_LOGIC;
    movei_2 : OUT STD_LOGIC;
    movei_3 : OUT STD_LOGIC;
    Bot1    : OUT STD_LOGIC;
    Bot2    : OUT STD_LOGIC;
    Bot3    : OUT STD_LOGIC
);
End CSR_Lab_3_Part1_main;



architecture Structural of CSR_Lab_3_Part1_main is

    -------------------------------------------------------------------
    -- Component Declarations
    -------------------------------------------------------------------
    component CSR_Lab_3_Part1_TD1 is
        port(
            Clk : in std_logic;
            outi : in std_logic;
            ini : in std_logic;
            in1 : in std_logic;
            event_event74_td_1 : in std_logic;
            movei : out std_logic;
            Bot1 : out std_logic;
            out_evt_event71_td_2 : out std_logic;
            Enable : in std_logic;
            Reset : in std_logic
        );
    end component;

    component CSR_Lab_3_Part1_TD2 is
        port(
            Clk : in std_logic;
            ini : in std_logic;
            outi_2 : in std_logic;
            event_event71_td_2 : in std_logic;
            event_event90_td_2 : in std_logic;
            movei_2 : out std_logic;
            Bot1 : out std_logic;
            Bot2 : out std_logic;
            out_evt_event74_td_1 : out std_logic;
            out_evt_event87_td_3 : out std_logic;
            Enable : in std_logic;
            Reset : in std_logic
        );
    end component;

    component CSR_Lab_3_Part1_TD3 is
        port(
            Clk : in std_logic;
            ini_2 : in std_logic;
            outi_3 : in std_logic;
            ini_3 : in std_logic;
            event_event87_td_3 : in std_logic;
            movei_3 : out std_logic;
            Bot2 : out std_logic;
            Bot3 : out std_logic;
            out_evt_event90_td_2 : out std_logic;
            Enable : in std_logic;
            Reset : in std_logic
        );
    end component;

    -------------------------------------------------------------------
    -- Event connection signals between components
    -------------------------------------------------------------------
    signal Bot1_TD1, Bot1_TD2 : std_logic;
    signal Bot2_TD2, Bot2_TD3 : std_logic;
    signal Bot3_TD3 : std_logic;
    
    signal event_event74_td_1, event_event71_td_2, event_event90_td_2, event_event87_td_3 : std_logic;
    signal out_evt_event71_td_2, out_evt_event74_td_1, out_evt_event90_td_2, out_evt_event87_td_3 : std_logic;

begin

    -------------------------------------------------------------------
    -- Component Instantiations
    -------------------------------------------------------------------

    U_CSR_Lab_3_Part1_TD1 : CSR_Lab_3_Part1_TD1
        port map(
            Clk => Clk,
            outi => outi,
            ini => ini,
            in1 => in1,
            event_event74_td_1 => event_event74_td_1,
            movei => movei,
            Bot1 => Bot1_TD1,
            out_evt_event71_td_2 => out_evt_event71_td_2,
            Enable => Enable,
            Reset => Reset
        );

    U_CSR_Lab_3_Part1_TD2 : CSR_Lab_3_Part1_TD2
        port map(
            Clk => Clk,
            ini => ini,
            outi_2 => outi_2,
            event_event71_td_2 => event_event71_td_2,
            event_event90_td_2 => event_event90_td_2,
            movei_2 => movei_2,
            Bot1 => Bot1_TD2,
            Bot2 => Bot2_TD2,
            out_evt_event74_td_1 => out_evt_event74_td_1,
            out_evt_event87_td_3 => out_evt_event87_td_3,
            Enable => Enable,
            Reset => Reset
        );

    U_CSR_Lab_3_Part1_TD3 : CSR_Lab_3_Part1_TD3
        port map(
            Clk => Clk,
            ini_2 => ini_2,
            outi_3 => outi_3,
            ini_3 => ini_3,
            event_event87_td_3 => event_event87_td_3,
            movei_3 => movei_3,
            Bot2 => Bot2_TD3,
            Bot3 => Bot3_TD3,
            out_evt_event90_td_2 => out_evt_event90_td_2,
            Enable => Enable,
            Reset => Reset
        );

    -------------------------------------------------------------------
    -- Event Interconnections (optional, depending on IOPT structure)
    -------------------------------------------------------------------
    
    Bot1 <= Bot1_TD1 OR Bot1_TD2;
    Bot2 <= Bot2_TD2 OR Bot2_TD3;
    Bot3 <= Bot3_TD3;
    
    event_event74_td_1 <= out_evt_event74_td_1;
    event_event71_td_2 <= out_evt_event71_td_2;
    event_event87_td_3 <= out_evt_event87_td_3;
    event_event90_td_2 <= out_evt_event90_td_2;

end Structural;
